import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import Header from "./_components/Header";
import AnimatedWrapper from "./_components/AnimatedWrapper";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Recipe Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/menu.png" sizes="any" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-100`}
      >
        <Header />

        <main className="mt-[200px]">
          <AnimatedWrapper>{children}</AnimatedWrapper>
        </main>

        <Script src="/smoothScroll.js" />
        <Footer />
      </body>
    </html>
  );
}
